### PR TITLE
qa/tasks/deepsea: implement active systemd units validation test

### PR DESCRIPTION
**Pull request by smithfarm**
and revamp _introspect_roles

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

File: qa/tasks/salt_manager.py [hunk 1]
```diff
@@ -227,18 +227,22 @@ def start_minions(self):
...
     def sync_pillar_data(self, quiet=True):
         cmd = "sudo salt \\* saltutil.sync_all"
         if quiet:
             cmd += " 2>/dev/null"
-        self.master_remote.run(args=cmd)
+        with safe_while(sleep=15, tries=10,
+                        action=cmd) as proceed:
+            while proceed():
+                output = StringIO()
+                self.master_remote.run(args=cmd, stdout=output)
```
Comment (kshtsk) [inline qa/tasks/salt_manager.py]: btw, you can now use:
```
if len(re.findall('Minion did not return', self.master_remote.sh(cmd))):
  log.info("Not all minions responded. Retrying...")
else:
  return None
```

Comment (smithfarm) [reply qa/tasks/salt_manager.py]: done

File: qa/tasks/deepsea.py [hunk 2]
```diff
@@ -29,6 +28,21 @@ def anchored(log_message):
     return "{}{}".format(deepsea_ctx['log_anchor'], log_message)
 
 
+def remote_run_script_as_root(remote, path, data, args=None):
```
Comment (kshtsk) [inline qa/tasks/deepsea.py]: I wonder if the usage of this method can be replaced by remote.sh_file?

Comment (smithfarm) [reply qa/tasks/deepsea.py]: That's worth investigating as a future optimization. Since this PR has passed all tests and is needed to make the CI green, I'm merging it now.

**Comment by smithfarm** [comment]
http://10.86.0.135:8081/ubuntu-2018-11-07_12:42:08-suse-wip-qa-storage-roles---basic-openstack/

Result: PASS

**Comment by smithfarm** [comment]
@kshtsk After merging this, all CI tests are failing with

```
2018-11-07T13:34:29.131 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 95, in run_tasks
    run_one_task(taskname, stack, timer, ctx=ctx, config=config)
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 74, in run_one_task
    manager.__enter__()
  File "/home/ubuntu/teuthology/teuthology/task/__init__.py", line 121, in __enter__
    self.begin()
  File "/home/ubuntu/src/github.com_SUSE_ceph_ses6/qa/tasks/deepsea.py", line 1300, in begin
    self.sm.sync_pillar_data(quiet=self.quiet_salt)
  File "/home/ubuntu/src/github.com_SUSE_ceph_ses6/qa/tasks/salt_manager.py", line 239, in sync_pillar_data
    self.master_remote.sh(cmd))
AttributeError: 'Remote' object has no attribute 'sh'
```

Which looks related to https://github.com/SUSE/teuthology/pull/165 - can you take a look?

**Comment by kshtsk** [comment]
@smithfarm this log does not help, where are you running it?

**Comment by smithfarm** [comment]
@kshtsk The CI is running it. I think the teuthology VM does not have your remote.sh teuthology patches yet.

**Comment by smithfarm** [comment]
@kshtsk Latest CI run: http://10.86.0.53:8081/ubuntu-2018-11-07_13:27:13-suse-ses6---basic-openstack/

**Comment by kshtsk** [comment]
@smithfarm for the future, always give the jenkins job url, it takes extra CPU to determine which CI have you been running your tests.

**Comment by kshtsk** [comment]
> @kshtsk Latest CI run: http://10.86.0.53:8081/ubuntu-2018-11-07_13:27:13-suse-ses6---basic-openstack/

the reason is obvious, the server teuthology instance is not updated teuthology code automatically.
usually, you need log in to the teuthology server and update teuthology to the recent version...
like `ssh ubuntu@... "cd teuthology ; git checkout master ; git pull ; git checkout ci ; git rebase master"`
I've just done this, please, reschedule your run.
