### PR TITLE
SES5: update to latest master (12.0.1)

### PR DESCRIPTION
**Pull request by smithfarm**
This update increments the version number to 12.0.1 and contains a fix for bsc#1031311

Note: there was a small conflict in ceph.spec.in

### CODE REVIEW

File: ceph.spec.in [hunk 1]
```diff
@@ -834,8 +845,9 @@ cmake .. \
 %endif
     $CEPH_EXTRA_CMAKE_ARGS \
 %if 0%{with ocf}
-    -DWITH_OCF=ON
+    -DWITH_OCF=ON \
 %endif
+    -DBOOST_J=%{_smp_ncpus}
```
Comment (smithfarm) [inline ceph.spec.in]: @rjfd @jan--f This is where I had to resolve the conflict.

**Comment by smithfarm** [comment]
Test build triggered in https://build.suse.de/package/show/Devel:Storage:5.0:Staging:Testing/ceph

**Comment by smithfarm** [comment]
Fails to build on ppc64le and s390x. In both cases the error is:

```
[  672s] [ 33%] Building CXX object src/CMakeFiles/common-objs.dir/common/simple_spin.cc.o
[  672s] /home/abuild/rpmbuild/BUILD/ceph-12.0.1+git.1491313394.3372162/src/common/simple_spin.cc:38:2: error: #error "Unknown architecture"
[  672s]  #error "Unknown architecture"
[  672s]   ^
[  672s] src/CMakeFiles/common-objs.dir/build.make:2415: recipe for target 'src/CMakeFiles/common-objs.dir/common/simple_spin.cc.o' failed
[  672s] make[2]: *** [src/CMakeFiles/common-objs.dir/common/simple_spin.cc.o] Error 1
```

**Comment by smithfarm** [comment]
Looks like a regression introduced by https://github.com/ceph/ceph/pull/14248 - reported it there for now.

**Comment by smithfarm** [comment]
Pushed a commit reverting upstream PR#14248 but will hold off until tomorrow - this looks like it might be a trivial fix (just need someone who knows a little bit of ppc64le and s390x assembler).

**Comment by smithfarm** [comment]
Dropped the revert and updated to an even more recent version of master to pick up https://github.com/ceph/ceph/pull/14310

**Comment by smithfarm** [comment]
Confirm that https://github.com/ceph/ceph/pull/14310 fixes the ppc64le build. Pushed another commit - currently being reviewed at https://github.com/ceph/ceph/pull/14337 - to address the s390x build failure.

**Comment by smithfarm** [comment]
Yet-another-test-build running at https://build.suse.de/package/show/Devel:Storage:5.0:Staging:Testing/ceph
